---
version: "2.1"
services:
  ytm-offline:
    image: aleixmt/ytm-manager-backend:latest
    depends_on:
      - postgres-db
    ports:
      - "0.0.0.0:5000:5000"
    volumes:
      - ./secrets:/usr/src/app/secrets
    restart: unless-stopped

  postgres-db:
    image: postgres
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_USER=ytm
      - POSTGRES_DB=ytm_backend
    ports:
      - "0.0.0.0:5432:5432"
    restart: unless-stopped
