---
version: "2.1"
services:
  ytm-offline:
    image: aleixmt/ytm-manager-backend:latest
    ports:
      - "0.0.0.0:5000:5000"
    volumes:
      - ./secrets:/usr/src/app/secrets
    restart: unless-stopped
    stdin_open: true
    tty: true
